<a href="https://colab.research.google.com/github/jnikem/pytorch-study/blob/main/sprint0_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import torch
print(np.__version__, torch.__version__)

2.0.2 2.11.0+cpu


In [ ]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.randn(3,3)

array([[ 1.12911533, -1.1166545 , -0.87780823],
       [ 0.38631036, -1.54426044,  0.54328574],
       [-2.43601111,  0.76770147, -0.33813403]])

In [ ]:
np.shape

<function shape at 0x7ab26bf3d230>

In [ ]:
np.dtype

numpy.dtype

In [ ]:
a = np.array([1, 2, 3])
b = np.zeros((3, 4))
c = np.arange(10)
d = np.random.randn(3, 3)

print(a.shape, a.dtype)
print(b.shape, b.dtype)
print(c.shape, c.dtype)
print(d.shape, d.dtype)

(3,) int64
(3, 4) float64
(10,) int64
(3, 3) float64


In [ ]:
a

array([1, 2, 3])

In [ ]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
d


array([[-0.6009743 ,  0.92804802,  0.80940187],
       [-0.12800834,  0.14728728, -1.4891093 ],
       [-0.20379017,  0.51759874, -0.88588501]])

In [ ]:
d

array([[-0.6009743 ,  0.92804802,  0.80940187],
       [-0.12800834,  0.14728728, -1.4891093 ],
       [-0.20379017,  0.51759874, -0.88588501]])

In [ ]:
a = np.arrange(10)

In [ ]:
a = np.arange(10)

In [ ]:
print(a[0])

0


In [ ]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
print(a[-1])

9


In [ ]:
print(a[2:5])

[2 3 4]


In [ ]:
print(a[:3])

[0 1 2]


In [ ]:
print(a[::2])

[0 2 4 6 8]


In [ ]:
b = np.zeros((3, 4))

In [ ]:
b[0,0] = 1

In [ ]:
b[1, :] = 5

In [ ]:
print(b)

[[1. 0. 0. 0.]
 [5. 5. 5. 5.]
 [0. 0. 0. 0.]]


In [ ]:
print(b[:,0])

[1. 5. 0.]


In [ ]:
a = np.array([1, 2, 3])
print(a + 1)          # 전체에 1씩 더하기 (루프 없이!)
print(a * 2)
print(a + a)           # 같은 shape끼리는 원소별 연산

c = np.array([[1,2,3],[4,5,6]])   # 2x3
d = np.array([10, 20, 30])           # shape (3,)
print(c + d)             # shape 다른데도 계산됨 — 이게 브로드캐스팅

[2 3 4]
[2 4 6]
[2 4 6]
[[11 22 33]
 [14 25 36]]


In [ ]:
e = np.array([[1,2],[3,4]])
f = np.array([[5,6],[7,8]])
print(e * f)     # 원소별 곱 (같은 자리끼리)
print(e @ f)      # 진짜 행렬곱 (선형대수의 그것)

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [3]:
import numpy as np
import torch
print(np.__version__, torch.__version__)

2.0.2 2.11.0+cpu


In [4]:
g = np.array([[1,2,3],[4,5,6]])
print(g.sum())            # 전체 합
print(g.sum(axis=0))     # 열끼리 합 (세로 방향)
print(g.sum(axis=1))     # 행끼리 합 (가로 방향)
print(g.mean(axis=0))

21
[5 7 9]
[ 6 15]
[2.5 3.5 4.5]


In [6]:
class Dog:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def bark(self):
    print(f"{self.name}가 짖습니다! 나이: {self.age}살")

d = Dog("초코", 3)
d.bark()
print(d.name)

초코가 짖습니다! 나이: 3살
초코


In [2]:
import numpy as np

class GradeBook:
  def __init__(self, name):
    self.name = name
    self.scores = np.array([]) # 빈 배열로 시작

  def add_score(self, score):
    self.scores = np.append(self.scores, score)

  def average(self):
    return self.scores.mean()

  def summary(self):
    print(f"{self.name}: 점수={self.scores}, 평균={self.average():.1f}")

In [3]:
gb = GradeBook("승민")
gb.add_score(85)
gb.add_score(92)
gb.add_score(78)
gb.summary()

승민: 점수=[85. 92. 78.], 평균=85.0


In [6]:
class Animal:
  def __init__(self, name):
    self.name = name
  def speak(self):
    print(f"{self.name}가 소리를 냅니다")

class Cat(Animal):  # Animal을 상속
  def speak(self):  # 오버라이드
    print(f"{self.name}가 야옹합니다")

In [7]:
c = Cat("나비")
c.speak()

나비가 야옹합니다
